services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "10M"
    networks:
      - rinha

  api1:
    image: scaputo88/rinha-2026-go:v3
    pull_policy: always
    environment:
      - PORT=8080
      - VPTREE_BIN=/data/vptree.bin
    restart: on-failure
    healthcheck:
      test: ["CMD", "/api", "--health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 90s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "170M"
    networks:
      - rinha

  api2:
    image: scaputo88/rinha-2026-go:v3
    pull_policy: always
    environment:
      - PORT=8080
      - VPTREE_BIN=/data/vptree.bin
    restart: on-failure
    healthcheck:
      test: ["CMD", "/api", "--health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 90s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "170M"
    networks:
      - rinha

networks:
  rinha:
    driver: bridge
